# Generated by Django 6.0.6 on 2026-06-25 09:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('boutiques', '0003_alter_boutique_proprietaire'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Depense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('categorie', models.CharField(choices=[('loyer', 'Loyer'), ('electricite', 'Électricité'), ('eau', 'Eau'), ('internet', 'Internet / Téléphone'), ('fournitures', 'Fournitures de bureau'), ('transport', 'Transport'), ('salaire', 'Salaire / Prime'), ('maintenance', 'Maintenance / Réparation'), ('publicite', 'Publicité / Marketing'), ('personnel', 'Dépense personnelle avancée'), ('autre', 'Autre')], default='autre', max_length=50)),
                ('type_depense', models.CharField(choices=[('boutique', 'Dépense boutique'), ('personnelle', 'Dépense personnelle avancée')], default='boutique', max_length=20)),
                ('justificatif', models.FileField(blank=True, null=True, upload_to='depenses/')),
                ('statut_remboursement', models.CharField(choices=[('na', 'Non applicable'), ('en_attente', 'En attente de remboursement'), ('rembourse', 'Remboursé')], default='na', max_length=20)),
                ('date_depense', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('boutique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depenses', to='boutiques.boutique')),
                ('effectuee_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='depenses_effectuees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dépense',
                'verbose_name_plural': 'Dépenses',
                'ordering': ['-date_depense'],
            },
        ),
    ]
