# Generated by Django 6.0.6 on 2026-06-12 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutiques', '0001_initial'),
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NiveauFidelite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('points_minimum', models.IntegerField(default=0)),
                ('remise_pourcentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('couleur', models.CharField(default='#9CA3AF', max_length=20)),
                ('icon', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Niveau de fidélité',
                'verbose_name_plural': 'Niveaux de fidélité',
                'ordering': ['points_minimum'],
            },
        ),
        migrations.AddField(
            model_name='client',
            name='date_dernier_achat',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='points_expires',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Recompense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('points_requis', models.IntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='recompenses/')),
                ('stock', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('boutique', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recompenses', to='boutiques.boutique')),
            ],
            options={
                'verbose_name': 'Récompense',
                'verbose_name_plural': 'Récompenses',
                'ordering': ['points_requis'],
            },
        ),
        migrations.CreateModel(
            name='EchangeRecompense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_utilises', models.IntegerField()),
                ('date_echange', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(default='valide', max_length=20)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='echanges', to='clients.client')),
                ('recompense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.recompense')),
            ],
            options={
                'verbose_name': 'Échange de récompense',
                'verbose_name_plural': 'Échanges de récompenses',
                'ordering': ['-date_echange'],
            },
        ),
    ]
