# Generated by Django 6.0.6 on 2026-06-18 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutiques', '0002_alter_boutique_proprietaire'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='boutiques',
            field=models.ManyToManyField(blank=True, related_name='utilisateurs', to='boutiques.boutique'),
        ),
    ]
