# Generated by Django 5.2.9 on 2026-01-06 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('boutiques', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('code_barre', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('reference', models.CharField(max_length=50, unique=True)),
                ('prix_achat', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prix_vente', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prix_promo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('stock_actuel', models.IntegerField(default=0)),
                ('stock_minimum', models.IntegerField(default=5)),
                ('stock_maximum', models.IntegerField(default=100)),
                ('unite', models.CharField(choices=[('unite', 'Unité'), ('kg', 'Kilogramme'), ('g', 'Gramme'), ('l', 'Litre'), ('ml', 'Millilitre'), ('m', 'Mètre'), ('cm', 'Centimètre'), ('paquet', 'Paquet'), ('carton', 'Carton')], default='unite', max_length=20)),
                ('image_principale', models.ImageField(blank=True, null=True, upload_to='produits/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('boutique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produits', to='boutiques.boutique')),
                ('categorie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produits', to='produits.categorie')),
            ],
            options={
                'verbose_name': 'Produit',
                'verbose_name_plural': 'Produits',
                'ordering': ['-created_at'],
                'unique_together': {('reference', 'boutique')},
            },
        ),
        migrations.CreateModel(
            name='ImageProduit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='produits/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='produits.produit')),
            ],
            options={
                'verbose_name': 'Image Produit',
                'verbose_name_plural': 'Images Produits',
            },
        ),
    ]
